### ISSUE TITLE
 Unable to retrieve images

### ISSUE THREAD

**Issue by bernard-ng** [glooby/pexels#1]
Following the documentation, we are asked to recover the different images thanks to a foreach loop. only the search function of the API returns an object of the type Guzzle Response and the latter is not convertible into an array.

#**Error**
I get the following error:
Can not use object of type GuzzleHttp\Message\Response as array

#**Fixe**
```
$images = json_decode($pexels->search('london')->getBody())->images;
foreach ($images as $image) {
 echo "<img src='{$image->src->small}' width='{$image->width}' heigth='{$image->height}'>"
}
```

**Comment by jcandan** [comment]
I am not sure why this issue was closed. The documentation does include an example response, which shows that `photos` is the correct property to use of the decoded json object, not `images`. I propose re-opening this issue, and fixing the documentation's provided loop example like so:

```
$images = json_decode($pexels->search('london')->getBody())->photos;
```

It might seem simple, but this little change will save someone the frustration of debugging a trivial documentation error.

**Comment by kilhage** [comment]
I merged @bernard-ng PR https://github.com/glooby/pexels/pull/2/files which should have fixed this issue but I can see that it probably was not 100%. I corrected the README according to your example @jcandan
